const VALUES = {
  CAPTION_BUTTON_SEARCH: "Search",
  CAPTION_BOOKED: "Booked",
  CAPTION_CENTER: "Center",
  CAPTION_AGE: "Min Age-",
  CAPTION_DOSE_ONE: "D1-",
  CAPTION_DOSE_TWO: "D2-",
  CAPTION_NOTAVAIABLE:'N/A',
};

export default VALUES;
